from vk_api.keyboard import VkKeyboard, VkKeyboardColor

keyboard_start = VkKeyboard()
keyboard_start.add_button("GTA 5 RP", VkKeyboardColor.POSITIVE,{"button": "GTA 5 RP"})
keyboard_start.add_button("MADJESTIK RP", VkKeyboardColor.SECONDARY )
keyboard_start.add_button("ARIZONA RP", VkKeyboardColor.SECONDARY )
keyboard_start.add_line()
keyboard_start.add_button("GRAND RP", VkKeyboardColor.SECONDARY )
keyboard_start.add_button("SMOTRARAGE", VkKeyboardColor.SECONDARY )
keyboard_start.add_button("RRP GTA V", VkKeyboardColor.SECONDARY )
keyboard_start.add_line()
keyboard_start.add_button("Меню", VkKeyboardColor.PRIMARY)
keyboard_start.add_button("Баланс", VkKeyboardColor.PRIMARY)

keyboard_balance = VkKeyboard()
keyboard_balance.add_button('Пополнить', VkKeyboardColor.POSITIVE)
keyboard_balance.add_button('Вывести', VkKeyboardColor.NEGATIVE)
keyboard_balance.add_line()
keyboard_balance.add_button('Меню', VkKeyboardColor.PRIMARY)

keyboard_choose_choose_server_gta5rp = VkKeyboard()
keyboard_choose_choose_server_gta5rp.add_button("Downtown", VkKeyboardColor.PRIMARY)
keyboard_choose_choose_server_gta5rp.add_button("Strawberry", VkKeyboardColor.PRIMARY)
keyboard_choose_choose_server_gta5rp.add_button("Vinewood", VkKeyboardColor.PRIMARY)
keyboard_choose_choose_server_gta5rp.add_button("Blackberry", VkKeyboardColor.PRIMARY)
keyboard_choose_choose_server_gta5rp.add_line()
keyboard_choose_choose_server_gta5rp.add_button("Insquad", VkKeyboardColor.PRIMARY)
keyboard_choose_choose_server_gta5rp.add_button("Sunrise", VkKeyboardColor.PRIMARY)
keyboard_choose_choose_server_gta5rp.add_button("Rainbow", VkKeyboardColor.PRIMARY)
keyboard_choose_choose_server_gta5rp.add_button("Richman", VkKeyboardColor.PRIMARY)
keyboard_choose_choose_server_gta5rp.add_line()
keyboard_choose_choose_server_gta5rp.add_button("Eclipse", VkKeyboardColor.PRIMARY)
keyboard_choose_choose_server_gta5rp.add_button("La Mesa", VkKeyboardColor.PRIMARY)
keyboard_choose_choose_server_gta5rp.add_button("Burton", VkKeyboardColor.PRIMARY)
keyboard_choose_choose_server_gta5rp.add_button("Rockford", VkKeyboardColor.PRIMARY)
keyboard_choose_choose_server_gta5rp.add_line()
keyboard_choose_choose_server_gta5rp.add_button("Alta", VkKeyboardColor.PRIMARY)
keyboard_choose_choose_server_gta5rp.add_button("Del Perro", VkKeyboardColor.PRIMARY)
keyboard_choose_choose_server_gta5rp.add_button("Davis", VkKeyboardColor.PRIMARY)
keyboard_choose_choose_server_gta5rp.add_button("Harmony", VkKeyboardColor.PRIMARY)
keyboard_choose_choose_server_gta5rp.add_line()
keyboard_choose_choose_server_gta5rp.add_button("Redwood", VkKeyboardColor.PRIMARY)
keyboard_choose_choose_server_gta5rp.add_line()
keyboard_choose_choose_server_gta5rp.add_button("Меню", VkKeyboardColor.PRIMARY)

keyboard_choose_choose_server_madjestik = VkKeyboard()
keyboard_choose_choose_server_madjestik.add_button("1 Server", VkKeyboardColor.PRIMARY)
keyboard_choose_choose_server_madjestik.add_button("2 Server", VkKeyboardColor.PRIMARY)
keyboard_choose_choose_server_madjestik.add_button("3 Server", VkKeyboardColor.PRIMARY)
keyboard_choose_choose_server_madjestik.add_button("4 Server", VkKeyboardColor.PRIMARY)
keyboard_choose_choose_server_madjestik.add_line()
keyboard_choose_choose_server_madjestik.add_button("5 Server", VkKeyboardColor.PRIMARY)
keyboard_choose_choose_server_madjestik.add_button("6 Server", VkKeyboardColor.PRIMARY)
keyboard_choose_choose_server_madjestik.add_button("7 Server", VkKeyboardColor.PRIMARY)
keyboard_choose_choose_server_madjestik.add_button("8 Server", VkKeyboardColor.PRIMARY)
keyboard_choose_choose_server_madjestik.add_line()
keyboard_choose_choose_server_madjestik.add_button("Меню", VkKeyboardColor.PRIMARY)

keyboard_choose_choose_server_Arizona= VkKeyboard()
keyboard_choose_choose_server_Arizona.add_button("Единый",VkKeyboardColor.PRIMARY)
keyboard_choose_choose_server_Arizona.add_line()
keyboard_choose_choose_server_Arizona.add_button("Меню",VkKeyboardColor.PRIMARY)

keyboard_choose_choose_server_RRP= VkKeyboard()
keyboard_choose_choose_server_RRP.add_button("1",VkKeyboardColor.PRIMARY)
keyboard_choose_choose_server_RRP.add_button("2",VkKeyboardColor.PRIMARY)
keyboard_choose_choose_server_RRP.add_button("3",VkKeyboardColor.PRIMARY)
keyboard_choose_choose_server_RRP.add_line()
keyboard_choose_choose_server_RRP.add_button("Меню",VkKeyboardColor.PRIMARY)

keyboard_choose_choose_server_GRAND= VkKeyboard()
keyboard_choose_choose_server_GRAND.add_button("Сервер 1",VkKeyboardColor.PRIMARY)
keyboard_choose_choose_server_GRAND.add_button("Сервер 2",VkKeyboardColor.PRIMARY)
keyboard_choose_choose_server_GRAND.add_button("Сервер 3",VkKeyboardColor.PRIMARY)
keyboard_choose_choose_server_GRAND.add_button("Сервер KAIF",VkKeyboardColor.PRIMARY)
keyboard_choose_choose_server_GRAND.add_line()
keyboard_choose_choose_server_GRAND.add_button("Меню",VkKeyboardColor.PRIMARY)

keyboard_choose_choose_server_SMOTRA= VkKeyboard()
keyboard_choose_choose_server_SMOTRA.add_button("Первый",VkKeyboardColor.PRIMARY)
keyboard_choose_choose_server_SMOTRA.add_line()
keyboard_choose_choose_server_SMOTRA.add_button("Меню",VkKeyboardColor.PRIMARY)

keyboard_buy_sale = VkKeyboard()
keyboard_buy_sale.add_button("Купить", VkKeyboardColor.PRIMARY)
keyboard_buy_sale.add_button("Продать", VkKeyboardColor.PRIMARY)
keyboard_buy_sale.add_line()
keyboard_buy_sale.add_button("Меню", VkKeyboardColor.PRIMARY)

keyboard_item = VkKeyboard(one_time=True)
keyboard_item.add_button("Одежда", VkKeyboardColor.PRIMARY)
keyboard_item.add_button("Недвижимость", VkKeyboardColor.PRIMARY)
keyboard_item.add_line()
keyboard_item.add_button("Машины", VkKeyboardColor.PRIMARY)
keyboard_item.add_button("Бизнес", VkKeyboardColor.PRIMARY)
keyboard_item.add_line()
keyboard_item.add_button("Оказание Услуг", VkKeyboardColor.PRIMARY)
keyboard_item.add_line()
keyboard_item.add_button("Меню", VkKeyboardColor.PRIMARY)

keyboard_chat_connect = VkKeyboard()
keyboard_chat_connect.add_button('Поддержка', VkKeyboardColor.PRIMARY.POSITIVE)

servers = ["Redwood", "Harmony", "Eclipse", "Davis", "Del Perro", "Alta", "Rockford", "Burton", "La Mesa", "Eclipse",
           "Richman", "Rainbow", "Sunrise", "Insquad", "Blackberry", "Vinewood", "Strawberry", "Downtown", "1 Server",
           "2 Server", "3 Server", "4 Server", "5 Server", "6 Server", "7 Server", "8 Server", 'Единый', "1", "2", "3",
           "Сервер 1", "Сервер 2", "Сервер 3", "Сервер KAIF", "Первый"]
items = ["Одежда", "Оказание Услуг", "Бизнес", "Машины", "Недвижимость"]
